# Generated by Django 3.0.3 on 2020-03-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cover_url', models.CharField(max_length=255)),
                ('genre_primary', models.CharField(max_length=255)),
                ('genre_secondary', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('release_code', models.CharField(max_length=255)),
                ('release_type', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('track_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('genre_primary', models.CharField(max_length=255)),
                ('genre_secondary', models.CharField(max_length=255)),
                ('song_id', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('track_number', models.IntegerField()),
                ('album_id', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
            ],
        ),
    ]
