# Generated by Django 3.0.3 on 2020-03-04 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200304_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='artist_name',
        ),
        migrations.AddField(
            model_name='song',
            name='album_id',
            field=models.ForeignKey(default='EMPTY', on_delete=django.db.models.deletion.CASCADE, to='catalog.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default='EMPTY', on_delete=django.db.models.deletion.CASCADE, to='catalog.Artist'),
        ),
    ]
