# Generated by Django 3.0.3 on 2020-03-04 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200304_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_id',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(db_column='album_id', default='EMPTY', on_delete=django.db.models.deletion.CASCADE, to='catalog.Album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(db_column='artist_name', on_delete=django.db.models.deletion.CASCADE, to='catalog.Artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_type',
            field=models.CharField(db_column='type', max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_name',
            field=models.CharField(db_column='album', max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(db_column='artist_name', default='EMPTY', on_delete=django.db.models.deletion.CASCADE, to='catalog.Artist'),
        ),
    ]
