# Generated by Django 3.0.3 on 2020-03-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
