# Generated by Django 3.0.3 on 2020-03-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_name',
        ),
    ]
